services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Syncs local files with the container
      - /app/node_modules # Prevents overwriting installed dependencies
    environment:
      - NODE_ENV=development
    env_file:
      - .env
